name: Python package

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] #, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2

      # Init. for Python version >3.x
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      # Check linting of the source
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 .
        continue-on-error: true

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt