name: Python package

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] #, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2

      # Init. for Python version >3.x
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Install RAI
      #- name: Install bare RAI
      #  run: |
      #    sudo apt-get install python3 python3-dev python3-numpy python3-pip python3-distutils
      #    echo 'export PATH="${PATH}:$HOME/.local/bin"' >> ~/.bashrc
      #    pip install --user jupyter nbconvert matplotlib pybind11 opencv-python 
      #    git clone https://github.com/MarcToussaint/rai.git
      #    cd rai
      #    make -j1 installUbuntuAll
      #    make -j4
      
      # Check linting of the source
      - name: Lint with flake8
        run: |
          pip install flake8
      # flake8 --extend-ignore=E402,W293,W504 .

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt